---

- name: smokey
  hosts: jumpbox
  roles:
  - osp-facts
  gather_facts: true
  become: true

- name: Run smokey
  hosts: frontends
  become: yes
  gather_facts: false

  tasks:
  - name: Connect to URI
    uri:
      url: http://{{ inventory_hostname }}
      return_content: yes
    register: result

  - debug: var=result

  - name: test output
    fail:
      msg: "FAILED!!"
    when: "'Welcome to Tomcat' not in result.content"
